### ISSUE TITLE
className vs class in JSX

### ISSUE THREAD

**Issue by staygrimm** [segmentio/deku#109]
React uses `className` within JSX because `class` is a reserved word, however it looks like Deku uses `class` and doesn't recognize `className`.

I was wondering your thoughts on this as [feross/standard](https://github.com/), a popular linter that doesn't provide any configuration, uses eslint and its React JSX linter which reports errors whenever `class` is used within JSX.

Before I bring this up in standard's issues I wanted to make sure you were already aware of this and made a conscious decision to use `class` over `className`.

**Comment by anthonyshort** [comment]
We're using standard to lint Deku now :) We chose to use just `class` because we're not supporting the older browsers throw errors about it being a reserved word for keys of objects. This means we can make it work more closely to native HTML.

We could add support for `className` that just maps over to `class` though if people keep slipping up and doing the React way.

**Comment by staygrimm** [comment]
Great, thanks for the swift response!  I've never used React myself so the distinction doesn't really matter to me.
