### ISSUE TITLE
Use Immutable State

### ISSUE THREAD

**Issue by anthonyshort** [segmentio/deku#26]
We'll eventually move all of the state on entities into the scene in an immutable object using Immstruct.

**Comment by Raynos** [comment]
Mercury has the same feature using `observ-struct` and pals. Works great for us :)

**Comment by anthonyshort** [comment]
Yeah I saw that :) I'm hoping to make the API completely transparent to the user, so they don't need to wrap every value in structs, but we'll see how that goes haha

**Comment by Raynos** [comment]
@anthonyshort 

I havn't had a change to write a `mercury.lift(complexObject)` yet.

One of the things I have optimized for is that in your rendering function you can just do `state.foo.bar.baz` instead of `state.get('foo.bar.baz')`

I optimized for "simplicity" in the render function, which is why I do shallow copies to avoid having to cast red black trees into javascript objects. If you do find yourself converting ImmStruct into plain JS objects you wasted the point of using ImmStruct :( 

The mutation interface does require `state.foo.bar.baz.set(newValue)` though. If you find a novel way to use a transparent mutation interface, id love to see it :)

**Comment by anthonyshort** [comment]
I haven't really looked into it yet, so I'll probably run into those issues. This is why I've been putting it off :) But thanks for the help. I might end up using `observ-struct` behind the scenes if Immstruct isn't as performant.

**Comment by anthonyshort** [comment]
Going to leave this up to the user to decide if they want to do this. With the upcoming `context` update we'll look at making that immutable behind the scenes later to speed up the re-rendering.
