### ISSUE TITLE
Pull existing information from the DOM

### ISSUE THREAD

**Issue by tcoats** [segmentio/deku#29]
Web components are interesting - an html element is rendered on the server, delivered to the browser where a script discovers the element, reads the information and adds behaviour. Deku could render the element on the server and attach to the element in the browser afterwards for behaviour.

At the moment I presume it does not attach to existing elements because deku has no reference to the element. Perhaps this could be changed?

[Github have an example](https://github.com/github/time-elements) where they render a custom time element which is picked up in the browser and localised, and perhaps continually updated.

Is this behaviour something deku might support?

Something hacky could be implemented on afterMount to find a sibling element but that does not seem elegant.

The benefit is that the data can be delivered in the page instead of through an additional JSON request. Even if the DOM text is JSON that is parsed and merged with props I think it's a nice addition.

**Comment by anthonyshort** [comment]
Virtual DOM libraries don't work exactly the same as web components, so it's a little tricky. But lets say we wanted to mount of bunch of small components around a page, instead of having one big single page app, you could use classes:

```js
var els = document.querySelectorAll('time');
var time = map(els, function(el){
  return Time.render(el, el.data);
});
```

Then you could do something like:

```html
<time data-is="local-time" data-datetime="2014-04-01T16:30:00-08:00"></time>
```

And they'll all be replaced by your component. You could abstract that a bit and do it for lots of different types of components at once when the page loads too.

**Comment by anthonyshort** [comment]
Alternatively, you could create Web Components that use deku behind the scenes, then you get the best of both :)

**Comment by tcoats** [comment]
Groovy, thank you. I suspected that deku can be used as part of the solution.
