### ISSUE TITLE
Trouble rendering component at the root of a tree

### ISSUE THREAD

**Issue by spenceralger** [segmentio/deku#33]
From what I can tell, I can only change the root tag once. After it is updated the first time it fails to update afterward. Here is a plunkr that reproduces the behavior I'm seeing: http://plnkr.co/edit/kOsqpnJ6v4vKLnlDYUtt?p=preview

1. click the login button
2. click the logout button
3. observe the error message in the console about `TypeError: Cannot read property 'insertBefore' of null`

It seems that the root of the tree is no longer related to the parent element, but I can't seem to wrap my head around why...

Let me know if I can help!

**Comment by anthonyshort** [comment]
Ah, nice catch! I think it's because I'm not updating the DOM element that is associated with a component instance in the renderer.


It actually shouldn't be too tricky to fix. It just needs to check the element after the diff and update it in this.elements. You could have a look in lib/renderer/html if you want to track it down. 




I think there's even a failing test already in there for that one too. 




To get around it for now, you could just avoid changing the element at the root of a component and it should be fine.

**Comment by anthonyshort** [comment]
Fixed :)

**Comment by spenceralger** [comment]
Woohoo! thanks @anthonyshort! Works like a charm
