### ISSUE TITLE
discussion: replace setState with a setter

### ISSUE THREAD

**Issue by yoshuawuyts** [segmentio/deku#37]
`this.setState` comes from React-land and to me always has felt a little clunky. Wouldn't it be neat if instead of using `this.setState`, `state` would be exposed as a getter / setter. The syntax would then become:
```js
// react style
onClick() {
  this.setState({ clicked: true });
}

// getter / setter
onClick() {
  this.state = { clicked: true };
}
```
To my knowledge `get` / `set` is optimized by V8 (and probably other engines too), so performance shouldn't be noticeably impacted.

By no means am I saying that `this.setState()` is bad, but I figured it'd be cool to think about alternative syntaxes that require less learning. If this is something you like, I can write a PR that implements this. Hope this is helpful. Thanks!

**Comment by anthonyshort** [comment]
I've thought about that, and it's a neat idea. Since you'd just do `this.state.foo = true` to automatically set that as pending in the background. One thing I'm trying to do is eliminate the use of `this` as much as possible, so that the components are dumb and basically just objects. I also eventually want to store all of the state in an immutable object so I'm not sure how that will affect the API yet.

One other way I've thought about doing it:

```
onClick(e, props, state) {
  state.set({ clicked: true });
}

// or 

onClick(e, props, state) {
  state.clicked = true;
}
```

This completely decouples all of the pending state and state reconciliation from the Entity and Component instances. It also means you're never fiddling with `this` everywhere and you can set state anywhere you have the `state` object.

One other thing to consider with the `state.clicked = true` style is that for the getters/setters to be setup you need to know what they all are. So you'd need to loop through all the keys and redefine the property with the setter each time.

**Comment by yoshuawuyts** [comment]
Oh, I'm totally +1 with removing all references to `this` (and forgetting that backbone classes ever existed). The second example your posted looks nicer, though performance may indeed be a bit of an issue.

Something that might be interesting (not sure how it would work out) would be to require state to be predefined, and then locked down through [`object.seal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal). That way all getters / setters can be predefined causing less lookups. Also adds some immutability to `deku` which might be cool (:
